"""Add training and validation data tables

Revision ID: 0dd5b7fcc451
Revises: 
Create Date: 2025-10-19 13:59:08.806962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd5b7fcc451'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('vital_temperature_c', sa.Float(), nullable=False),
    sa.Column('vital_heart_rate', sa.Integer(), nullable=False),
    sa.Column('vital_blood_pressure_systolic', sa.Integer(), nullable=True),
    sa.Column('vital_blood_pressure_diastolic', sa.Integer(), nullable=True),
    sa.Column('symptom_list', sa.JSON(), nullable=False),
    sa.Column('pmh_list', sa.JSON(), nullable=True),
    sa.Column('current_medications', sa.JSON(), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('free_text_notes', sa.Text(), nullable=True),
    sa.Column('target_disease', sa.Integer(), nullable=False),
    sa.Column('target_tests', sa.JSON(), nullable=False),
    sa.Column('target_medications', sa.JSON(), nullable=False),
    sa.Column('condition_name', sa.String(), nullable=False),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_training_data_condition_name'), 'training_data', ['condition_name'], unique=False)
    op.create_index(op.f('ix_training_data_id'), 'training_data', ['id'], unique=False)
    op.create_table('validation_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('vital_temperature_c', sa.Float(), nullable=False),
    sa.Column('vital_heart_rate', sa.Integer(), nullable=False),
    sa.Column('vital_blood_pressure_systolic', sa.Integer(), nullable=True),
    sa.Column('vital_blood_pressure_diastolic', sa.Integer(), nullable=True),
    sa.Column('symptom_list', sa.JSON(), nullable=False),
    sa.Column('pmh_list', sa.JSON(), nullable=True),
    sa.Column('current_medications', sa.JSON(), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('free_text_notes', sa.Text(), nullable=True),
    sa.Column('target_disease', sa.Integer(), nullable=False),
    sa.Column('target_tests', sa.JSON(), nullable=False),
    sa.Column('target_medications', sa.JSON(), nullable=False),
    sa.Column('condition_name', sa.String(), nullable=False),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_validation_data_condition_name'), 'validation_data', ['condition_name'], unique=False)
    op.create_index(op.f('ix_validation_data_id'), 'validation_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_data_id'), table_name='validation_data')
    op.drop_index(op.f('ix_validation_data_condition_name'), table_name='validation_data')
    op.drop_table('validation_data')
    op.drop_index(op.f('ix_training_data_id'), table_name='training_data')
    op.drop_index(op.f('ix_training_data_condition_name'), table_name='training_data')
    op.drop_table('training_data')
    # ### end Alembic commands ###
