"""Add clinical feedback and outcome tables

Revision ID: e988348448f4
Revises: 0dd5b7fcc451
Create Date: 2025-10-19 14:49:46.907275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e988348448f4'
down_revision: Union[str, None] = '0dd5b7fcc451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
